source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

# Based on CocoaPods 1.0

inhibit_all_warnings! # Hide Xcode warnings from pods

abstract_target 'BasePods' do
    # Networking
    pod 'AFNetworking'
    pod 'ObjcAssociatedObjectHelpers', '~> 2.0'

    target 'AFNetworking+RetryPolicy Example' do
    end
end
